title: Joe's GitHub Page
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My page doesn't really have much of a description at this point. kind of a boring 1-pager :P

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
